// Convenience re-exports of the Go API types generated by tygo (src/api/gen).
import type { Ref as DeckRef } from "./gen/decks";
import type { Change as ReencodeChange } from "./gen/reencode";
import type { Experiment, Generation } from "./gen/experiments";
import type { Job } from "./gen/jobs";

export type { FileStats } from "./gen/bag";
export type {
  Batch as ReencodeBatch,
  Change as ReencodeChange,
  Counts as ReencodeCounts,
  Decided as ReencodeDecided,
  Detail as ReencodeDetail,
  Estimate as ReencodeEstimate,
  Item as ReencodeItem,
  Progress as ReencodeProgress,
  Settings as ReencodeSettings,
} from "./gen/reencode";
export type {
  DeleteResult as FileDeleteResult,
  FileKind,
  Listing as FileListing,
  MoveResult as FileMoveResult,
  Node as FileNode,
  Problem as FileProblem,
  Progress as FileTransferProgress,
  PutResult as FilePutResult,
  Report as FileTransferReport,
  Summary as FileSummary,
} from "./gen/files";
export type { Analysis, Image, ImageScore, PipelineStats, PurgeResult, Stats, Tag, ThumbInfo } from "./gen/library";
export type { ImageQuery, Scope, Sort } from "./gen/query";
export type { IDPair, Metric, Pair, Ranking, Run, Summary } from "./gen/scoring";
export type {
  Cluster,
  Pair as DedupPair,
  Params as DedupParams,
  Resolution,
  Scan,
} from "./gen/dedup";
export type {
  FileReport as ImportFileReport,
  Options as ImportOptions,
  Progress as ImportProgress,
  Report as ImportReport,
  RefreshReport,
  ThumbReport,
} from "./gen/importer";
export type {
  FileReport as ExportFileReport,
  Options as ExportOptions,
  Progress as ExportProgress,
  Report as ExportReport,
} from "./gen/exporter";
export type { Job } from "./gen/jobs";
export type { Result as BackupResult } from "./gen/backup";
export type {
  CategoryOptions,
  CheckResult,
  DanbooruOptions,
  Failure as AnalysisFailure,
  Options as AnalysisOptions,
  Outcome as AnalysisOutcome,
  Plan as AnalysisPlan,
  Progress as AnalysisProgress,
  Report as AnalysisReport,
  Settings as AnalysisSettings,
  TagFilter,
  TaggerCheck,
  TaggerOptions,
} from "./gen/analysis";
export type { Installation as TaggerInstallation, LocalStatus as TaggerStatus } from "./gen/tagger";
export type {
  Applied,
  Device as ComfyDevice,
  Dim,
  Input as WorkflowInput,
  InputSpec,
  Node as WorkflowNode,
  NodeInfo,
  Override,
  Range as SweepRange,
  ServerInfo as ComfyInfo,
  Sweep,
} from "./gen/comfy";
export type {
  Experiment,
  Failure as GenerationFailure,
  Generation,
  MoveResult,
  PlanSummary,
  Progress as GenerateProgress,
  Request as GenerateRequest,
  Result as GenerateResult,
  Run as GenerationRun,
  Settings as ComfySettings,
  Version as WorkflowVersion,
  Workflow as WorkflowTemplate,
  WorkflowDetail,
} from "./gen/experiments";

export type {
  Added as DeckAdded,
  Deck,
  Detail as DeckDetail,
  Ref as DeckRef,
  Settings as SlideshowSettings,
} from "./gen/decks";

export interface ImageDetail {
  image: import("./gen/library").Image;
  scores: import("./gen/library").ImageScore[];
  analyses: import("./gen/library").Analysis[];
  /** How the image was generated, when it came from an experiment. */
  generation?: GenerationDetail;
  /** The slide decks the image is in. */
  decks: DeckRef[];
  /** Re-encodes that replaced the image's file, oldest first. */
  reencodes: ReencodeChange[];
}

/** A generated image, and whether its workflow template has changed since. */
export interface GenerationDetail extends Generation {
  current: boolean;
  templateExists: boolean;
}

export interface ExperimentView extends Experiment {
  /** The generation job running in the experiment, if any. */
  job?: Job;
}

export interface ComfyCheck {
  ok: boolean;
  message: string;
  info?: import("./gen/comfy").ServerInfo;
}

export interface ComfyNodes {
  nodes: Record<string, import("./gen/comfy").NodeInfo>;
  missing: string[];
  error?: string;
}

export interface AnalysisKeyInfo {
  set: boolean;
  hint?: string;
  fromEnv: boolean;
  env: string;
  store: string;
}

export interface AnalysisSettingsView {
  settings: import("./gen/analysis").Settings;
  key: AnalysisKeyInfo;
  defaults: Record<string, string>;
}

export interface FsEntry {
  name: string;
  path: string;
}

export interface FsListing {
  path: string;
  parent: string;
  dirs: FsEntry[];
  images: number;
  roots: FsEntry[];
  home: string;
  bagDir: string;
  separator: string;
}

export interface ScanView {
  scan: import("./gen/dedup").Scan;
  threshold: number;
  clusters: import("./gen/dedup").Cluster[];
  images: import("./gen/library").Image[];
}

export interface Rankings {
  metric: import("./gen/scoring").Metric;
  rankings: import("./gen/scoring").Ranking[];
}

export interface BackupDownload {
  token: string;
  filename: string;
  bytes: number;
  url: string;
}
