// Convenience re-exports of the Go API types generated by tygo (src/api/gen).
export type { FileStats } from "./gen/bag";
export type { Image, ImageScore, PurgeResult, Stats, Tag } from "./gen/library";
export type { ImageQuery, Scope, Sort } from "./gen/query";
export type { IDPair, Metric, Pair, Ranking, Run, Summary } from "./gen/scoring";
export type {
  Cluster,
  Pair as DedupPair,
  Params as DedupParams,
  Resolution,
  Scan,
} from "./gen/dedup";
export type {
  FileReport as ImportFileReport,
  Options as ImportOptions,
  Progress as ImportProgress,
  Report as ImportReport,
} from "./gen/importer";
export type {
  FileReport as ExportFileReport,
  Options as ExportOptions,
  Progress as ExportProgress,
  Report as ExportReport,
} from "./gen/exporter";
export type { Job } from "./gen/jobs";
export type { Result as BackupResult } from "./gen/backup";

export interface ImageDetail {
  image: import("./gen/library").Image;
  scores: import("./gen/library").ImageScore[];
}

export interface FsEntry {
  name: string;
  path: string;
}

export interface FsListing {
  path: string;
  parent: string;
  dirs: FsEntry[];
  images: number;
  roots: FsEntry[];
  home: string;
  bagDir: string;
  separator: string;
}

export interface ScanView {
  scan: import("./gen/dedup").Scan;
  threshold: number;
  clusters: import("./gen/dedup").Cluster[];
  images: import("./gen/library").Image[];
}

export interface Rankings {
  metric: import("./gen/scoring").Metric;
  rankings: import("./gen/scoring").Ranking[];
}

export interface BackupDownload {
  token: string;
  filename: string;
  bytes: number;
  url: string;
}
